spring:
  application:
    name: jmcomic-gateway
  cloud:
    loadbalancer:
      cache:
        enabled: true
        ttl: 30s
        capacity: 256
        health-check:
          path: /actuator/health
          initial-delay: 0s
      retry:
        enabled: true
      configurations: default
      enabled: true
server:
  port: 7813
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    ip-address: localhost
  client:
    service-url:
      defaultZone: http://localhost:7891/eureka/
    registry-fetch-interval-seconds: 30
    eureka-server-connect-timeout-seconds: 5
    eureka-server-read-timeout-seconds: 8
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    root: WARN
    reactor: WARN
    org.springframework: WARN
    com.lazy.jmcomic: INFO